# Cargo-deny configuration for formatparse
# See https://github.com/EmbarkStudios/cargo-deny

[licenses]
# Allow common permissive licenses
# Any license not in this list will be denied
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "Unlicense",
    "CC0-1.0",
]

[advisories]
# Vulnerability database
db-path = "~/.cargo/advisory-db"
# Unmaintained crates - check all dependencies
unmaintained = "all"
# Yanked crates
yanked = "warn"
# Ignore specific advisories (use sparingly)
# ignore = ["RUSTSEC-XXXX-XXXX"]

[bans]
# Multiple versions of the same crate
multiple-versions = "warn"
# Wildcard dependencies
wildcards = "deny"

